"use strict";
const CONFIG=Object.freeze({apiUrl:window.DASHBOARD_API_URL||"/api/dashboard",timezone:"Asia/Kolkata",refreshMs:30000});
const state={data:null,lastUpdate:null,activePage:"overview",expanded:new Set(),signalDates:new Set(),historyTradeDates:new Set(),historyScanDates:new Set(),selectedTrade:null,calendarDate:dateInputValue(new Date()),calendarImpacts:new Set(["All"]),calendarDates:new Set(),calendar:null,backtest:null};
const $=id=>document.getElementById(id);const $$=selector=>Array.from(document.querySelectorAll(selector));
function escapeHtml(value){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function number(value,digits=2){const n=Number(value);return Number.isFinite(n)?n.toLocaleString("en-IN",{minimumFractionDigits:digits,maximumFractionDigits:digits}):"—";}
function inr(value){const n=Number(value);return Number.isFinite(n)?`₹${n.toLocaleString("en-IN",{minimumFractionDigits:0,maximumFractionDigits:2})}`:"—";}
function price(value){return number(value,2);}
function timestamp(value){if(!value)return "—";const d=new Date(value);if(Number.isNaN(d.getTime()))return "—";return new Intl.DateTimeFormat("en-IN",{timeZone:CONFIG.timezone,day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit",hour12:false}).format(d);}
function dateLabel(value){if(!value)return "Unknown date";const d=new Date(`${value}T00:00:00`);if(Number.isNaN(d.getTime()))return "Unknown date";return new Intl.DateTimeFormat("en-IN",{timeZone:CONFIG.timezone,weekday:"short",day:"2-digit",month:"short",year:"numeric"}).format(d);}
function dateInputValue(value){const d=value instanceof Date?value:new Date(value);const p=new Intl.DateTimeFormat("en-CA",{timeZone:CONFIG.timezone,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(d);const m=Object.fromEntries(p.map(x=>[x.type,x.value]));return `${m.year}-${m.month}-${m.day}`;}
function dateKey(value){if(!value)return "unknown";const d=new Date(value);if(Number.isNaN(d.getTime()))return "unknown";return dateInputValue(d);}
function clock(){return new Intl.DateTimeFormat("en-IN",{timeZone:CONFIG.timezone,hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(new Date());}
function safeApiError(status,text){const compact=String(text||"").replace(/\s+/g," ").trim();return compact?`HTTP ${status}: ${compact.slice(0,240)}`:`HTTP ${status}`;}
async function readJsonResponse(response,context="Request"){const text=await response.text();let payload=null;if(text.trim()){try{payload=JSON.parse(text);}catch(error){const type=response.headers.get("content-type")||"unknown content type";throw new Error(`${context} returned invalid JSON (${type}). ${safeApiError(response.status,text)}`);}}if(!response.ok)throw new Error(payload?.error||safeApiError(response.status,text)||`${context} failed`);if(!payload||typeof payload!=="object")throw new Error(`${context} returned an empty response.`);return payload;}
function direction(signal){const s=String(signal||"NO_SIGNAL").toUpperCase();if(s==="BUY")return{text:"BUY",icon:"🟢",cls:"buy"};if(s==="SELL")return{text:"SELL",icon:"🔴",cls:"sell"};if(s==="NEUTRAL")return{text:"NEUTRAL",icon:"⚪",cls:"neutral"};return{text:"NO SIGNAL",icon:"·",cls:"neutral"};}
function assetInfo(symbol){const rows=state.data?.universe?.asset_metadata||[];return rows.find(row=>row.symbol===symbol||row.ticker===symbol)||null;}
function assetLabel(symbol,fallback){const info=assetInfo(symbol);return info?.label||fallback||symbol||"Unknown asset";}
function strategyInfo(value){const rows=state.data?.strategies||[];return rows.find(row=>row.id===value||row.name===value)||null;}
function strategyLabel(value){return strategyInfo(value)?.name||value||"Strategy";}
function canonicalSignals(){const rows=Array.isArray(state.data?.signals)?state.data.signals:[];const latest=new Map();rows.filter(row=>["BUY","SELL"].includes(String(row.signal||row.direction||"").toUpperCase())).forEach(row=>{const key=row.signal_key||[row.strategy,row.symbol,row.signal||row.direction,row.timestamp].join("|");const previous=latest.get(key);if(!previous||String(row.updated_at||row.created_at||row.timestamp)>String(previous.updated_at||previous.created_at||previous.timestamp))latest.set(key,row);});return [...latest.values()].sort((a,b)=>String(b.timestamp).localeCompare(String(a.timestamp)));}
function supportedBacktestAssets(strategyId){const strategy=strategyInfo(strategyId);const allowed=new Set(strategy?.assets||[]);return (state.data?.backtest_assets||[]).filter(asset=>!allowed.size||allowed.has(asset.key||asset.ticker));}
function freshness(signal){const status=String(signal?.freshness||"UNKNOWN").toUpperCase();return status==="FRESH"?{label:"FRESH",cls:"fresh"}:status==="STALE"?{label:"STALE",cls:"stale"}:{label:status||"UNKNOWN",cls:"stale"};}
function ageText(signal){const minutes=Number(signal?.age_minutes);if(!Number.isFinite(minutes)||minutes<0)return "Unavailable";return minutes<60?`${Math.floor(minutes)} min ago`:`${Math.floor(minutes/60)} hr ${Math.floor(minutes%60)} min ago`;}
function keyFor(prefix,item,index){const raw=item?.id||item?.signal_key||item?.timestamp||item?.closed_at||`${index}`;return `${prefix}:${raw}:${item?.symbol||item?.strategy||item?.plan?.strategy||"item"}`;}
function expandButton(key,label){const open=state.expanded.has(key);return `<button class="expand-button" type="button" data-expand="${escapeHtml(key)}" aria-expanded="${open}" aria-label="${open?"Collapse":"Expand"} ${escapeHtml(label)}">${open?"⌃":"⌄"}</button>`;}
function signalCard(signal,index){const key=keyFor("signal",signal,index),d=direction(signal.signal),age=freshness(signal),symbol=signal.symbol||signal.asset||"Unknown asset",label=assetLabel(symbol,signal.label),strategy=strategyLabel(signal.strategy),open=state.expanded.has(key),timeframe=signal.timeframe||strategyInfo(signal.strategy)?.timeframes?.[0]||"—";const details=open?`<div class="expand-content"><div class="detail-grid"><div><span>Strategy</span><b>${escapeHtml(strategy)}</b></div><div><span>Direction</span><b>${d.icon} ${d.text}</b></div><div><span>Timeframe</span><b>${escapeHtml(timeframe)}</b></div><div><span>Actionable</span><b>${signal.actionable===true?"YES":"NO"}</b></div><div><span>Freshness</span><b class="${age.cls}">${age.label}</b></div><div><span>Candle closed</span><b>${escapeHtml(timestamp(signal.timestamp))}</b></div><div><span>Age</span><b>${escapeHtml(ageText(signal))}</b></div><div><span>Pipeline</span><b>${escapeHtml(signal.pipeline_status||"—")}</b></div><div><span>Telegram</span><b>${escapeHtml(signal.delivery?.status||"NOT_SENT")}</b></div><div><span>Send count</span><b>${number(signal.send_count||signal.send_state?.send_count,0)} / 2</b></div><div><span>First sent</span><b>${escapeHtml(timestamp(signal.first_sent_at||signal.send_state?.first_sent_at))}</b></div></div><div class="reason"><span>Strategy reason</span><p>${escapeHtml(signal.reason||"No reason supplied by runtime.")}</p></div></div>`:"";const hasLevels=signal.has_trade_levels===true||[signal.entry,signal.take_profit,signal.stop_loss].every(value=>Number.isFinite(Number(value)));const lifecycle=String(signal.pipeline_status||signal.delivery?.status||"RECORDED").replaceAll("_"," ");const summary=hasLevels?`${d.text} · Entry ${price(signal.entry)} · Target ${price(signal.take_profit)} · Stop ${price(signal.stop_loss)}`:`${d.text} · ${lifecycle} · Signal details unavailable`;return `<article class="signal-card ${d.cls} ${open?"expanded":""} ${hasLevels?"has-levels":"incomplete"}"><div class="card-main" data-expand="${escapeHtml(key)}"><div class="signal-leading"><span class="direction-icon">${d.icon}</span><div><strong>${escapeHtml(label)}</strong><small>${escapeHtml(summary)}</small></div></div><div class="card-state"><span class="signal-side ${d.cls}">${d.text}</span>${expandButton(key,symbol)}</div></div>${details}</article>`;}
function tradeCard(trade,index){const key=keyFor("trade",trade,index),plan=trade.plan||trade,side=String(plan.side||trade.type||"").toUpperCase(),d=direction(side),open=state.expanded.has(key),status=String(trade.status||"OPEN").toUpperCase(),symbol=trade.symbol||plan.symbol||"Paper trade",label=assetLabel(symbol,trade.label||plan.label),strategy=strategyLabel(plan.strategy||trade.strategy),qty=plan.quantity??trade.qty,plannedRisk=plan.planned_risk??trade.planned_risk,pnl=trade.pnl;const details=open?`<div class="expand-content"><div class="detail-grid"><div><span>Strategy</span><b>${escapeHtml(strategy)}</b></div><div><span>Account</span><b>${escapeHtml(String(trade.account||"nifty").toUpperCase())}</b></div><div><span>Entry</span><b>${price(plan.entry??trade.entry)}</b></div><div><span>Stop Loss</span><b class="negative">${price(plan.stop_loss??trade.sl)}</b></div><div><span>Take Profit</span><b class="positive">${price(plan.take_profit??trade.tp)}</b></div><div><span>Quantity</span><b>${number(qty,4)}</b></div><div><span>Planned risk</span><b>${inr(plannedRisk)}</b></div><div><span>Signal candle</span><b>${escapeHtml(timestamp(plan.signal_timestamp||trade.signal_ts))}</b></div>${status==="CLOSED"?`<div><span>Exit</span><b>${price(trade.exit_price)}</b></div><div><span>P/L</span><b class="${Number(pnl)>=0?"positive":"negative"}">${inr(pnl)}</b></div><div><span>Exit reason</span><b>${escapeHtml(trade.exit_reason||trade.result||"—")}</b></div><div><span>Closed</span><b>${escapeHtml(timestamp(trade.closed_at||trade.exit_timestamp))}</b></div>`:""}</div></div>`:"";return `<article class="trade-card ${d.cls} ${open?"expanded":""}"><div class="card-main" data-expand="${escapeHtml(key)}"><div class="signal-leading"><span class="direction-icon">${d.icon}</span><div><strong>${escapeHtml(label)}</strong><small>${escapeHtml(strategy)} · ${escapeHtml(side||"—")}</small></div></div><div class="card-state"><span class="trade-status ${status.toLowerCase()}">${status}</span>${expandButton(key,symbol)}</div></div>${details}</article>`;}
function empty(message,icon="·",detail="There is nothing to display in the current snapshot."){return `<div class="empty-state"><span>${icon}</span><strong>${escapeHtml(message)}</strong><small>${escapeHtml(detail)}</small></div>`;}
function groupByDate(items,timeField){const groups=new Map();items.forEach(item=>{const value=item?.[timeField],key=dateKey(value);if(!groups.has(key))groups.set(key,{label:dateLabel(key),items:[]});groups.get(key).items.push(item);});return Array.from(groups.entries()).sort((a,b)=>b[0].localeCompare(a[0])).map(([,group])=>group);}
function groupedCards(items,renderer,timeField){const groups=groupByDate(items,timeField);if(!groups.length)return "";return groups.map(group=>`<section class="date-group"><div class="date-heading"><h3>${escapeHtml(group.label)}</h3><span>${group.items.length} record${group.items.length===1?"":"s"}</span></div><div class="stack">${group.items.map(renderer).join("")}</div></section>`).join("");}
function renderSignalChart(){const signals=canonicalSignals(),days=[],today=new Date();for(let i=13;i>=0;i--){const d=new Date(today);d.setDate(d.getDate()-i);days.push({key:dateKey(d),label:new Intl.DateTimeFormat("en-IN",{timeZone:CONFIG.timezone,day:"2-digit",month:"short"}).format(d),count:0});}const map=new Map(days.map(d=>[d.key,d]));signals.forEach(s=>{const row=map.get(dateKey(s.timestamp));if(row)row.count++;});if(!signals.length){$("signalActivityChart").innerHTML=empty("No signal activity yet","◇","The graph will populate when a BUY or SELL signal is detected, including stale signals.");return;}const max=Math.max(1,...days.map(d=>d.count)),width=720,height=230,left=28,right=10,top=16,bottom=38,plotW=width-left-right,plotH=height-top-bottom,barW=Math.max(12,plotW/days.length*.55);const bars=days.map((d,i)=>{const x=left+i*plotW/days.length+(plotW/days.length-barW)/2,h=d.count/max*plotH,y=top+plotH-h;return `<rect class="chart-bar" x="${x.toFixed(1)}" y="${y.toFixed(1)}" width="${barW.toFixed(1)}" height="${Math.max(2,h).toFixed(1)}" rx="4"><title>${escapeHtml(d.label)} · ${d.count} signal${d.count===1?"":"s"}</title></rect><text class="chart-label" x="${(x+barW/2).toFixed(1)}" y="${height-14}" text-anchor="middle">${escapeHtml(d.label)}</text>`;}).join("");$("signalActivityChart").innerHTML=`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Signal activity for the last 14 days"><line class="chart-axis" x1="${left}" y1="${top+plotH}" x2="${width-right}" y2="${top+plotH}"/><text class="chart-y" x="8" y="${top+plotH+4}">0</text>${bars}</svg>`;}
function renderEquityLine(points,{width=720,height=230,label="Equity curve"}={}){const safe=points.filter(p=>Number.isFinite(Number(p.equity)));if(!safe.length)return "";const values=safe.map(p=>Number(p.equity)),min=Math.min(...values),max=Math.max(...values),pad=Math.max(1,(max-min)*.12);const lo=min-pad,hi=max+pad||1,left=18,right=10,top=16,bottom=32,plotW=width-left-right,plotH=height-top-bottom;const xy=safe.map((p,i)=>{const x=left+(safe.length===1?plotW/2:i*plotW/(safe.length-1));const y=top+plotH-(Number(p.equity)-lo)/(hi-lo)*plotH;return [x,y];});const line=xy.map((p,i)=>`${i?"L":"M"}${p[0].toFixed(1)} ${p[1].toFixed(1)}`).join(" ");const area=`${line} L${xy[xy.length-1][0].toFixed(1)} ${(top+plotH).toFixed(1)} L${xy[0][0].toFixed(1)} ${(top+plotH).toFixed(1)} Z`;const start=safe[0],end=safe[safe.length-1];return `<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="${escapeHtml(label)}"><line class="chart-grid" x1="${left}" y1="${top+plotH/2}" x2="${width-right}" y2="${top+plotH/2}"/><line class="chart-axis" x1="${left}" y1="${top+plotH}" x2="${width-right}" y2="${top+plotH}"/><path class="equity-area" d="${area}"/><path class="equity-line" d="${line}"/><circle class="equity-point" cx="${xy[0][0].toFixed(1)}" cy="${xy[0][1].toFixed(1)}" r="3"><title>Start · ${inr(start.equity)}</title></circle><circle class="equity-point" cx="${xy[xy.length-1][0].toFixed(1)}" cy="${xy[xy.length-1][1].toFixed(1)}" r="3"><title>Current · ${inr(end.equity)}</title></circle><text class="chart-y" x="${left}" y="12">${escapeHtml(inr(hi))}</text><text class="chart-y" x="${left}" y="${height-8}">${escapeHtml(inr(lo))}</text></svg>`;}

/* remaining existing functions are intentionally unchanged */
