"use strict";
const CONFIG=Object.freeze({apiUrl:window.DASHBOARD_API_URL||"/api/dashboard",timezone:"Asia/Kolkata",refreshMs:30000});
const state={data:null,lastUpdate:null,activePage:"overview",expanded:new Set(),signalDates:new Set(),historyTradeDates:new Set(),historyScanDates:new Set(),selectedTrade:null,calendarDate:dateInputValue(new Date()),calendarImpacts:new Set(["All"]),calendarDates:new Set(),calendar:null,backtest:null};
const $=id=>document.getElementById(id);const $$=selector=>Array.from(document.querySelectorAll(selector));
function escapeHtml(value){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function number(value,digits=2){const n=Number(value);return Number.isFinite(n)?n.toLocaleString("en-IN",{minimumFractionDigits:digits,maximumFractionDigits:digits}):"—";}
function inr(value){const n=Number(value);return Number.isFinite(n)?`₹${n.toLocaleString("en-IN",{minimumFractionDigits:0,maximumFractionDigits:2})}`:"—";}
function price(value){return number(value,2);}
function timestamp(value){if(!value)return "—";const d=new Date(value);if(Number.isNaN(d.getTime()))return "—";return new Intl.DateTimeFormat("en-IN",{timeZone:CONFIG.timezone,day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit",hour12:false}).format(d);}
function dateLabel(value){if(!value)return "Unknown date";const d=new Date(`${value}T00:00:00`);if(Number.isNaN(d.getTime()))return "Unknown date";return new Intl.DateTimeFormat("en-IN",{timeZone:CONFIG.timezone,weekday:"short",day:"2-digit",month:"short",year:"numeric"}).format(d);}
function dateInputValue(value){const d=value instanceof Date?value:new Date(value);const p=new Intl.DateTimeFormat("en-CA",{timeZone:CONFIG.timezone,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(d);const m=Object.fromEntries(p.map(x=>[x.type,x.value]));return `${m.year}-${m.month}-${m.day}`;}
function dateKey(value){if(!value)return "unknown";const d=new Date(value);if(Number.isNaN(d.getTime()))return "unknown";return dateInputValue(d);}
function clock(){return new Intl.DateTimeFormat("en-IN",{timeZone:CONFIG.timezone,hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(new Date());}
function direction(signal){const s=String(signal||"NO_SIGNAL").toUpperCase();if(s==="BUY")return{text:"BUY",icon:"🟢",cls:"buy"};if(s==="SELL")return{text:"SELL",icon:"🔴",cls:"sell"};if(s==="NEUTRAL")return{text:"NEUTRAL",icon:"⚪",cls:"neutral"};return{text:"NO SIGNAL",icon:"·",cls:"neutral"};}function assetInfo(symbol){const rows=state.data?.universe?.asset_metadata||[];return rows.find(row=>row.symbol===symbol||row.ticker===symbol)||null;}
function assetLabel(symbol,fallback){const info=assetInfo(symbol);return info?.label||fallback||symbol||"Unknown asset";}
function strategyInfo(value){const rows=state.data?.strategies||[];return rows.find(row=>row.id===value||row.name===value)||null;}
function strategyLabel(value){return strategyInfo(value)?.name||value||"Strategy";}
function canonicalSignals(){const rows=Array.isArray(state.data?.signals)?state.data.signals:[];const latest=new Map();rows.filter(row=>["BUY","SELL"].includes(String(row.signal||row.direction||"").toUpperCase())).forEach(row=>{const key=row.signal_key||[row.strategy,row.symbol,row.signal||row.direction,row.timestamp].join("|");const previous=latest.get(key);if(!previous||String(row.updated_at||row.created_at||row.timestamp)>String(previous.updated_at||previous.created_at||previous.timestamp))latest.set(key,row);});return [...latest.values()].sort((a,b)=>String(b.timestamp).localeCompare(String(a.timestamp)));}
function supportedBacktestAssets(strategyId){const strategy=strategyInfo(strategyId);const allowed=new Set(strategy?.assets||[]);return (state.data?.backtest_assets||[]).filter(asset=>!allowed.size||allowed.has(asset.key||asset.ticker));}
function freshness(signal){const status=String(signal?.freshness||"UNKNOWN").toUpperCase();return status==="FRESH"?{label:"FRESH",cls:"fresh"}:status==="STALE"?{label:"STALE",cls:"stale"}:{label:status||"UNKNOWN",cls:"stale"};}
function ageText(signal){const minutes=Number(signal?.age_minutes);if(!Number.isFinite(minutes)||minutes<0)return "Unavailable";return minutes<60?`${Math.floor(minutes)} min ago`:`${Math.floor(minutes/60)} hr ${Math.floor(minutes%60)} min ago`;}
function keyFor(prefix,item,index){const raw=item?.id||item?.signal_key||item?.timestamp||item?.closed_at||`${index}`;return `${prefix}:${raw}:${item?.symbol||item?.strategy||item?.plan?.strategy||"item"}`;}
function expandButton(key,label){const open=state.expanded.has(key);return `<button class="expand-button" type="button" data-expand="${escapeHtml(key)}" aria-expanded="${open}" aria-label="${open?"Collapse":"Expand"} ${escapeHtml(label)}">${open?"⌃":"⌄"}</button>`;}
function signalCard(signal,index){const key=keyFor("signal",signal,index),d=direction(signal.signal),age=freshness(signal),symbol=signal.symbol||signal.asset||"Unknown asset",label=assetLabel(symbol,signal.label),strategy=strategyLabel(signal.strategy),open=state.expanded.has(key),timeframe=signal.timeframe||strategyInfo(signal.strategy)?.timeframes?.[0]||"—";const details=open?`<div class="expand-content"><div class="detail-grid"><div><span>Strategy</span><b>${escapeHtml(strategy)}</b></div><div><span>Direction</span><b>${d.icon} ${d.text}</b></div><div><span>Timeframe</span><b>${escapeHtml(timeframe)}</b></div><div><span>Freshness</span><b class="${age.cls}">${age.label}</b></div><div><span>Candle closed</span><b>${escapeHtml(timestamp(signal.timestamp))}</b></div><div><span>Age</span><b>${escapeHtml(ageText(signal))}</b></div><div><span>Pipeline</span><b>${escapeHtml(signal.pipeline_status||"—")}</b></div><div><span>Telegram</span><b>${escapeHtml(signal.delivery?.status||"NOT_SENT")}</b></div><div><span>Send count</span><b>${number(signal.send_count||signal.send_state?.send_count,0)} / 2</b></div><div><span>First sent</span><b>${escapeHtml(timestamp(signal.first_sent_at||signal.send_state?.first_sent_at))}</b></div></div><div class="reason"><span>Strategy reason</span><p>${escapeHtml(signal.reason||"No reason supplied by runtime.")}</p></div></div>`:"";const levels=`Entry ${price(signal.entry)} · Target ${price(signal.take_profit)} · Stop ${price(signal.stop_loss)}`;return `<article class="signal-card ${d.cls} ${open?"expanded":""}"><div class="card-main" data-expand="${escapeHtml(key)}"><div class="signal-leading"><span class="direction-icon">${d.icon}</span><div><strong>${escapeHtml(label)}</strong><small>${d.text} · ${escapeHtml(levels)}</small></div></div><div class="card-state"><span class="signal-side ${d.cls}">${d.text}</span>${expandButton(key,symbol)}</div></div>${details}</article>`;}
function tradeCard(trade,index){const key=keyFor("trade",trade,index),plan=trade.plan||trade,side=String(plan.side||trade.type||"").toUpperCase(),d=direction(side),open=state.expanded.has(key),status=String(trade.status||"OPEN").toUpperCase(),symbol=trade.symbol||plan.symbol||"Paper trade",label=assetLabel(symbol,trade.label||plan.label),strategy=strategyLabel(plan.strategy||trade.strategy),qty=plan.quantity??trade.qty,plannedRisk=plan.planned_risk??trade.planned_risk,pnl=trade.pnl;const details=open?`<div class="expand-content"><div class="detail-grid"><div><span>Strategy</span><b>${escapeHtml(strategy)}</b></div><div><span>Account</span><b>${escapeHtml(String(trade.account||"nifty").toUpperCase())}</b></div><div><span>Entry</span><b>${price(plan.entry??trade.entry)}</b></div><div><span>Stop Loss</span><b class="negative">${price(plan.stop_loss??trade.sl)}</b></div><div><span>Take Profit</span><b class="positive">${price(plan.take_profit??trade.tp)}</b></div><div><span>Quantity</span><b>${number(qty,4)}</b></div><div><span>Planned risk</span><b>${inr(plannedRisk)}</b></div><div><span>Signal candle</span><b>${escapeHtml(timestamp(plan.signal_timestamp||trade.signal_ts))}</b></div>${status==="CLOSED"?`<div><span>Exit</span><b>${price(trade.exit_price)}</b></div><div><span>P/L</span><b class="${Number(pnl)>=0?"positive":"negative"}">${inr(pnl)}</b></div><div><span>Exit reason</span><b>${escapeHtml(trade.exit_reason||trade.result||"—")}</b></div><div><span>Closed</span><b>${escapeHtml(timestamp(trade.closed_at||trade.exit_timestamp))}</b></div>`:""}</div></div>`:"";return `<article class="trade-card ${d.cls} ${open?"expanded":""}"><div class="card-main" data-expand="${escapeHtml(key)}"><div class="signal-leading"><span class="direction-icon">${d.icon}</span><div><strong>${escapeHtml(label)}</strong><small>${escapeHtml(strategy)} · ${escapeHtml(side||"—")}</small></div></div><div class="card-state"><span class="trade-status ${status.toLowerCase()}">${status}</span>${expandButton(key,symbol)}</div></div>${details}</article>`;}
function empty(message,icon="·",detail="There is nothing to display in the current snapshot."){return `<div class="empty-state"><span>${icon}</span><strong>${escapeHtml(message)}</strong><small>${escapeHtml(detail)}</small></div>`;}
function groupByDate(items,timeField){const groups=new Map();items.forEach(item=>{const value=item?.[timeField],key=dateKey(value);if(!groups.has(key))groups.set(key,{label:dateLabel(key),items:[]});groups.get(key).items.push(item);});return Array.from(groups.entries()).sort((a,b)=>b[0].localeCompare(a[0])).map(([,group])=>group);}
function groupedCards(items,renderer,timeField){const groups=groupByDate(items,timeField);if(!groups.length)return "";return groups.map(group=>`<section class="date-group"><div class="date-heading"><h3>${escapeHtml(group.label)}</h3><span>${group.items.length} record${group.items.length===1?"":"s"}</span></div><div class="stack">${group.items.map(renderer).join("")}</div></section>`).join("");}
function renderSignalChart(){const signals=canonicalSignals(),days=[],today=new Date();for(let i=13;i>=0;i--){const d=new Date(today);d.setDate(d.getDate()-i);days.push({key:dateKey(d),label:new Intl.DateTimeFormat("en-IN",{timeZone:CONFIG.timezone,day:"2-digit",month:"short"}).format(d),count:0});}const map=new Map(days.map(d=>[d.key,d]));signals.forEach(s=>{const row=map.get(dateKey(s.timestamp));if(row)row.count++;});if(!signals.length){$("signalActivityChart").innerHTML=empty("No signal activity yet","◇","The graph will populate when a BUY or SELL signal is detected, including stale signals.");return;}const max=Math.max(1,...days.map(d=>d.count)),width=720,height=230,left=28,right=10,top=16,bottom=38,plotW=width-left-right,plotH=height-top-bottom,barW=Math.max(12,plotW/days.length*.55);const bars=days.map((d,i)=>{const x=left+i*plotW/days.length+(plotW/days.length-barW)/2,h=d.count/max*plotH,y=top+plotH-h;return `<rect class="chart-bar" x="${x.toFixed(1)}" y="${y.toFixed(1)}" width="${barW.toFixed(1)}" height="${Math.max(2,h).toFixed(1)}" rx="4"><title>${escapeHtml(d.label)} · ${d.count} signal${d.count===1?"":"s"}</title></rect><text class="chart-label" x="${(x+barW/2).toFixed(1)}" y="${height-14}" text-anchor="middle">${escapeHtml(d.label)}</text>`;}).join("");$("signalActivityChart").innerHTML=`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Signal activity for the last 14 days"><line class="chart-axis" x1="${left}" y1="${top+plotH}" x2="${width-right}" y2="${top+plotH}"/><text class="chart-y" x="8" y="${top+plotH+4}">0</text>${bars}</svg>`;}
function renderOverview(){const data=state.data||{},signals=canonicalSignals(),trades=Array.isArray(data.trades)?data.trades:[],open=trades.filter(t=>String(t.status||"").toUpperCase()==="OPEN"),system=data.system||{},online=String(system.status||"").toUpperCase()==="ONLINE",scan=data.scan||{};$("overviewSystem").textContent=system.status||"WAITING";$("overviewSignalCount").textContent=Number(data.signal_summary?.total_directional??signals.length);$("overviewAssetCount").textContent=Number(data.universe?.count||0);$("overviewUpdated").textContent=state.lastUpdate?timestamp(state.lastUpdate):"—";const signalPill=$("heroSignalPill"),assetPill=$("heroAssetPill"),updatePill=$("heroUpdatePill");if(signalPill)signalPill.textContent=`${signals.length} ACTIVE SIGNAL${signals.length===1?"":"S"}`;if(assetPill)assetPill.textContent=`${Number(data.universe?.count||0)} ASSETS WATCHING`;if(updatePill)updatePill.textContent=online?"● SYSTEM ONLINE":"● SYSTEM WAITING";$("versionBadge").textContent=`v${escapeHtml(data.version||"2.0.0")}`;$("overviewSignals").innerHTML=signals.length?signals.slice(0,5).map(signalCard).join(""):empty("No signal records","◇",String(scan.status).toUpperCase()==="COMPLETE"?"The last completed scan found no approved directional signal to dispatch.":"No completed scan has been recorded yet.");}
function tradeDateValue(trade){return trade.closed_at||trade.exit_timestamp||trade.opened_at||trade.created_at||trade.timestamp||trade.signal_ts||trade.plan?.signal_timestamp;}
function tradeGroupKey(date){return `trade-date:${date}`;}
function renderTradeRow(trade,index){const plan=trade.plan||trade,side=String(plan.side||trade.type||"").toUpperCase(),d=direction(side),status=String(trade.status||"OPEN").toUpperCase(),symbol=trade.symbol||plan.symbol||"Paper trade",label=assetLabel(symbol,trade.label||plan.label),strategy=strategyLabel(plan.strategy||trade.strategy),entry=plan.entry??trade.entry,pnl=trade.pnl;return `<article class="trade-row ${d.cls}" data-trade-index="${index}"><div class="trade-row-main"><div class="trade-row-identity"><span class="direction-icon">${d.icon}</span><div><strong>${escapeHtml(label)}</strong><small>${escapeHtml(strategy)} · ${escapeHtml(side||"—")}</small></div></div><div class="trade-row-price"><span>Entry</span><b>${price(entry)}</b></div><div class="trade-row-price"><span>${status==="CLOSED"?"P/L":"Risk"}</span><b class="${status==="CLOSED"&&Number(pnl)<0?"negative":status==="CLOSED"&&Number(pnl)>=0?"positive":""}">${status==="CLOSED"?inr(pnl):inr(plan.planned_risk??trade.planned_risk)}</b></div><span class="trade-status ${status.toLowerCase()}">${status}</span><button class="trade-detail-button" type="button" data-trade-index="${index}" aria-label="View ${escapeHtml(label)} details">View</button></div></article>`;}
function renderTrades(){const trades=Array.isArray(state.data?.trades)?state.data.trades:[],filtered=trades.filter(t=>state.tradeFilter==="all"||String(t.status||"OPEN").toLowerCase()===state.tradeFilter),open=trades.filter(t=>String(t.status||"").toUpperCase()==="OPEN"),closed=trades.filter(t=>String(t.status||"").toUpperCase()==="CLOSED");$("tradesTotalCount").textContent=trades.length;$("tradesOpenCount").textContent=open.length;$("tradesClosedCount").textContent=closed.length;$("tradesResultCount").textContent=`${filtered.length} trade${filtered.length===1?"":"s"}`;$$('[data-trade-filter]').forEach(b=>b.classList.toggle("active",b.dataset.tradeFilter===state.tradeFilter));if(!filtered.length){$("tradesList").innerHTML=empty(state.tradeFilter==="open"?"No open paper trades":"No trades found","◈");return;}const grouped=new Map();filtered.forEach((trade,index)=>{const key=dateKey(tradeDateValue(trade));if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push({trade,index});});const ordered=[...grouped.entries()].sort((a,b)=>b[0].localeCompare(a[0]));if(!state.tradeDates.size&&ordered[0])state.tradeDates.add(tradeGroupKey(ordered[0][0]));$("tradesList").innerHTML=ordered.map(([date,rows])=>{const key=tradeGroupKey(date),openDate=state.tradeDates.has(key);return `<section class="trade-date-group ${openDate?"is-open":""}"><button class="trade-date-toggle" type="button" data-trade-date="${escapeHtml(key)}" aria-expanded="${openDate}"><span><b>${escapeHtml(dateLabel(date))}</b><small>${rows.length} trade${rows.length===1?"":"s"}</small></span><i>${openDate?"⌃":"⌄"}</i></button>${openDate?`<div class="trade-date-rows">${rows.map(row=>renderTradeRow(row.trade,row.index)).join("")}</div>`:""}</section>`;}).join("");}
function renderScanStatus(){const scan=state.data?.scan||{},status=String(scan.status||"NOT_RUN").toUpperCase();const el=$("scanStatus");if(!el)return;if(status==="COMPLETE"){el.innerHTML=`<div><span>Latest scan</span><b>${escapeHtml(timestamp(scan.at))}</b><small>${number(scan.checked,0)} checked · ${number(scan.directional,0)} directional · ${number(scan.sent,0)} dispatched</small></div>`;return;}el.innerHTML=`<div class="scan-warning"><span>Scan status</span><b>No completed scan recorded since runtime start.</b><small>A zero signal count is different from an unscanned universe.</small></div>`;}
function signalMatchesFilter(signal){const side=String(signal?.signal||signal?.direction||"").toLowerCase(),fresh=String(signal?.freshness||"").toLowerCase();if(state.signalDirection!=="all"&&side!==state.signalDirection)return false;if(state.signalFreshness!=="all"&&fresh!==state.signalFreshness)return false;return true;}
function signalDateKey(date){return `signal-date:${date}`;}
function renderSignalDateGroups(signals){const groups=new Map();signals.forEach(signal=>{const date=dateKey(signal.timestamp);if(!groups.has(date))groups.set(date,[]);groups.get(date).push(signal);});const ordered=[...groups.entries()].sort((a,b)=>b[0].localeCompare(a[0]));if(!state.signalDates.size&&ordered[0])state.signalDates.add(signalDateKey(ordered[0][0]));return ordered.map(([date,rows])=>{const key=signalDateKey(date),open=state.signalDates.has(key),buys=rows.filter(x=>String(x.signal||x.direction||"").toUpperCase()==="BUY").length,sells=rows.length-buys;return `<section class="signal-date-group ${open?"is-open":""}"><button class="signal-date-toggle" type="button" data-signal-date="${escapeHtml(key)}" aria-expanded="${open}"><span><b>${escapeHtml(dateLabel(date))}</b><small>${rows.length} signal${rows.length===1?"":"s"} · ${buys} BUY · ${sells} SELL</small></span><i>${open?"⌃":"⌄"}</i></button>${open?`<div class="signal-date-rows">${rows.map(signalCard).join("")}</div>`:""}</section>`;}).join("");}
function renderSignals(){const all=canonicalSignals(),signals=all;$("signalsResultCount").textContent=`${signals.length} signal${signals.length===1?"":"s"}`;$("signalsList").innerHTML=signals.length?renderSignalDateGroups(signals):empty("No signals yet","◇","Detected BUY and SELL signals will appear here when the runtime produces them.");}
function historyDateKey(prefix,date){return `history-${prefix}-date:${date}`;}
function scanDateValue(row){return row?.completed_at||row?.created_at||row?.timestamp||row?.run_at||row?.started_at||row?.updated_at;}
function renderHistoryScanRow(row){const p=row?.payload||{},strategy=strategyLabel(row?.strategy_id||row?.strategy||"Strategy"),status=String(row?.status||"RECORDED").toUpperCase(),checked=number(p.checked,0),directional=number(p.directional,0),sent=number(p.sent,0),errors=number(p.errors,0);return `<article class="history-scan-row"><div class="history-scan-identity"><strong>${escapeHtml(strategy)}</strong><small>${escapeHtml(timestamp(scanDateValue(row)))}</small></div><span class="history-scan-status">${escapeHtml(status)}</span><div class="history-scan-metrics"><span>${checked} checked</span><span>${directional} directional</span><span>${sent} sent</span><span>${errors} errors</span></div></article>`;}
function renderHistoryDateGroups(rows,kind){const groups=new Map();rows.forEach(row=>{const date=dateKey(kind==="trade"?tradeDateValue(row.trade):scanDateValue(row.scan));if(!groups.has(date))groups.set(date,[]);groups.get(date).push(row);});const ordered=[...groups.entries()].sort((a,b)=>b[0].localeCompare(a[0])),openSet=kind==="trade"?state.historyTradeDates:state.historyScanDates;if(!openSet.size&&ordered[0])openSet.add(historyDateKey(kind,ordered[0][0]));return ordered.map(([date,items])=>{const key=historyDateKey(kind,date),open=openSet.has(key),noun=kind==="trade"?"trade":"scan";return `<section class="history-date-group ${open?"is-open":""}"><button class="history-date-toggle" type="button" data-history-date="${escapeHtml(key)}" data-history-kind="${kind}" aria-expanded="${open}"><span><b>${escapeHtml(dateLabel(date))}</b><small>${items.length} ${noun}${items.length===1?"":"s"}</small></span><i>${open?"⌃":"⌄"}</i></button>${open?`<div class="history-date-rows">${kind==="trade"?items.map(row=>renderTradeRow(row.trade,row.index)).join(""):items.map(row=>renderHistoryScanRow(row.scan)).join("")}</div>`:""}</section>`;}).join("");}
function renderHistory(){const trades=Array.isArray(state.data?.trades)?state.data.trades:[],closedRows=trades.map((trade,index)=>({trade,index})).filter(row=>String(row.trade.status||"").toUpperCase()==="CLOSED"),closed=closedRows.map(row=>row.trade),pnlValues=closed.map(t=>Number(t.pnl)).filter(Number.isFinite),winners=pnlValues.filter(v=>v>0).length,latestDate=closedRows.map(row=>dateKey(tradeDateValue(row.trade))).filter(x=>x!=="unknown").sort().at(-1),dailyRows=latestDate?closedRows.filter(row=>dateKey(tradeDateValue(row.trade))===latestDate):[],dailyPnl=dailyRows.reduce((sum,row)=>sum+(Number(row.trade.pnl)||0),0);$("historyClosedCount").textContent=closedRows.length;$("historyDailyPnl").textContent=latestDate?inr(dailyPnl):"—";$("historyWinRate").textContent=pnlValues.length?Math.round(winners/pnlValues.length*100)+"%":"—";$("historyResultCount").textContent=closedRows.length+" trade"+(closedRows.length===1?"":"s");$("historyList").innerHTML=closedRows.length?renderHistoryDateGroups(closedRows,"trade"):empty("No completed trades","◷","Completed paper trades will appear here grouped by date.");}
function calendarDayKey(day){return `calendar-day:${day}`;}
function renderCalendar(){
  const calendar=state.calendar||{},days=Array.isArray(calendar.days)?calendar.days:[],items=Array.isArray(calendar.items)?calendar.items:[],status=String(calendar.status||"UNKNOWN").toUpperCase(),available=["ONLINE","CACHED"].includes(status),counts=calendar.counts||{};
  const total=Number(counts.high||0)+Number(counts.medium||0)+Number(counts.low||0)+Number(counts.holiday||0);
  $("calendarStatus").innerHTML=`<span class="inline-status"><span class="news-dot ${available?"online":"offline"}"></span><b>${escapeHtml(status)}</b><small>${escapeHtml(calendar.message||"No calendar status available.")}${calendar.fetched_at?` · Saved ${escapeHtml(timestamp(calendar.fetched_at))}`:""}</small></span>`;
  $("impactCountall").textContent=number(total||items.length,0);
  $("impactCounthigh").textContent=number(counts.high||0,0);
  $("impactCountmedium").textContent=number(counts.medium||0,0);
  $("impactCountother").textContent=number(Number(counts.low||0)+Number(counts.holiday||0),0);
  $("calendarResultCount").textContent=`${items.length} event${items.length===1?"":"s"} · ${days.length} date${days.length===1?"":"s"}`;
  $("calendarItems").innerHTML=days.length?calendarDateGroups(days):empty(status==="OFFLINE"?"Calendar source unavailable":"No upcoming events","◉",calendar.message||"The calendar cache has no upcoming events yet.");
}
function calendarDateGroups(days){
  if(!state.calendarDates)state.calendarDates=new Set();
  if(!state.calendarDates.size&&days[0])state.calendarDates.add(calendarDayKey(days[0].date));
  return days.map((day,index)=>{
    const key=calendarDayKey(day.date),open=state.calendarDates.has(key),items=Array.isArray(day.items)?day.items:[];
    const today=index===0?"TODAY · ":"";
    return `<section class="calendar-date-group ${open?"is-open":""}">
      <button class="calendar-date-toggle" type="button" data-calendar-date-group="${escapeHtml(key)}" aria-expanded="${open}">
        <span><b>${today}${escapeHtml(day.label||dateLabel(day.date))}</b><small>${items.length} scheduled event${items.length===1?"":"s"} · High ${number(day.counts?.high,0)} · Medium ${number(day.counts?.medium,0)}</small></span>
        <i>${open?"⌃":"⌄"}</i>
      </button>
      ${open?`<div class="calendar-date-events">${calendarTimeline(items)}</div>`:""}
    </section>`;
  }).join("");
}
function calendarTimeline(items){
  const rank={High:0,Medium:1,Low:2,Holiday:3};
  const timeValue=value=>{const s=String(value||"").trim();const m=s.match(/(\d{1,2}):(\d{2})/);return m?Number(m[1])*60+Number(m[2]):-1;};
  return [...items].sort((a,b)=>timeValue(a.time)-timeValue(b.time)||((rank[a.impact]??9)-(rank[b.impact]??9))).map(calendarCard).join("");
}
function calendarCard(item,index){
  const key=keyFor("calendar",item,index),impact=String(item.impact||"Low").toLowerCase(),open=state.expanded.has(key);
  const details=open?`<div class="calendar-details"><div><span>Actual</span><b>${escapeHtml(item.actual||"—")}</b></div><div><span>Forecast</span><b>${escapeHtml(item.forecast||"—")}</b></div><div><span>Previous</span><b>${escapeHtml(item.previous||"—")}</b></div></div>`:"";
  return `<article class="calendar-item impact-${escapeHtml(impact)} ${open?"expanded":""}">
    <div class="calendar-time"><strong>${escapeHtml(item.time||"All day")}</strong><small>IST</small></div>
    <div class="calendar-event">
      <div class="calendar-meta"><span class="currency-code">${escapeHtml(item.currency||"ALL")}</span><b class="impact-pill ${escapeHtml(impact)}">${escapeHtml(item.impact||"Low")}</b>${expandButton(key,"event")}</div>
      <strong>${escapeHtml(item.title||"Economic event")}</strong>
      <small>${item.actual?`Actual ${escapeHtml(item.actual)}`:item.forecast?`Forecast ${escapeHtml(item.forecast)}`:"Scheduled event"}${item.previous?` · Previous ${escapeHtml(item.previous)}`:""}</small>
      ${details}
    </div>
  </article>`;
}
function renderTools(){const data=state.data||{},universe=Array.isArray(data.universe?.symbols)?data.universe.symbols:[],strategies=Array.isArray(data.strategies)?data.strategies:[],accounts=Array.isArray(data.accounts?.data)?data.accounts.data:[];const strategySelect=$("backtestStrategy"),currentStrategy=strategySelect.value;strategySelect.innerHTML=strategies.map(strategy=>`<option value="${escapeHtml(strategy.id)}">${escapeHtml(strategy.name)} · v${escapeHtml(strategy.version)}</option>`).join("");if([...strategySelect.options].some(o=>o.value===currentStrategy))strategySelect.value=currentStrategy;const assets=supportedBacktestAssets(strategySelect.value),select=$("backtestSymbol"),current=select.value,groups={};assets.forEach(asset=>(groups[asset.group]??=[]).push(asset));select.innerHTML=Object.entries(groups).map(([group,rows])=>`<optgroup label="${escapeHtml(group)}">${rows.map(asset=>`<option value="${escapeHtml(asset.key||asset.ticker)}">${escapeHtml(asset.label)}</option>`).join("")}</optgroup>`).join("");if([...select.options].some(o=>o.value===current))select.value=current;$("universeGrid").innerHTML=universe.map(s=>`<span>${escapeHtml(assetLabel(s,s))}</span>`).join("");$("accountsGrid").innerHTML=accounts.map(a=>`<article><b>${escapeHtml(String(a.name).toUpperCase())}</b><span>${inr(a.balance)} · ${number(a.trades_today,0)}/${number(a.daily_trade_limit,0)} trades</span><small>${inr(a.remaining_planned_risk)} planned risk remaining</small></article>`).join("");$("versionText").textContent=`v${data.version||"2.0.0"}`;$("whatsNewList").innerHTML=(data.whats_new||[]).map(item=>`<li>${escapeHtml(item)}</li>`).join("");$("candleSchedule").innerHTML=["10:15|First close","11:15|Hourly close","12:15|Hourly close","13:15|Hourly close","14:15|Hourly close","15:15|Final close"].map(item=>{const [time,label]=item.split("|");return `<span><b>${time}</b><small>${label}</small></span>`;}).join("");$("diagnostics").innerHTML=`<article><span>API</span><b>Connected</b></article><article><span>Provider</span><b>${escapeHtml(data.system?.provider||data.health?.provider||"UNKNOWN")}</b></article><article><span>Timezone</span><b>${escapeHtml(data.system?.timezone||CONFIG.timezone)}</b></article><article><span>Snapshot</span><b>${escapeHtml(timestamp(data.generated_at))}</b></article>`;applyAppearanceControls();if(state.backtest)renderBacktest(state.backtest);}
function renderBacktest(result){const status=$("backtestStatus"),box=$("backtestResults");if(!result){box.hidden=true;return;}if(result.ok===false){status.className="backtest-status error";status.textContent=`Backtest failed: ${result.error||"Unknown error"}`;box.hidden=true;return;}status.className="backtest-status success";status.textContent=`${result.strategy} · ${result.asset?.label||result.symbol} · ${result.period} · ${number(result.candle_count,0)} candles`;const daily=Array.isArray(result.daily)?result.daily:[],max=Math.max(1,...daily.map(x=>x.total));const width=720,height=230,left=28,right=10,top=18,bottom=40,plotW=width-left-right,plotH=height-top-bottom,barW=Math.max(10,plotW/Math.max(1,daily.length)*.5);const bars=daily.map((row,i)=>{const x=left+i*plotW/daily.length+(plotW/daily.length-barW)/2,h=row.total/max*plotH,y=top+plotH-h;return `<rect class="backtest-bar" x="${x.toFixed(1)}" y="${y.toFixed(1)}" width="${barW.toFixed(1)}" height="${Math.max(2,h).toFixed(1)}" rx="4"><title>${escapeHtml(row.date)} · BUY ${row.buy} · SELL ${row.sell}</title></rect><text class="chart-label" x="${(x+barW/2).toFixed(1)}" y="${height-14}" text-anchor="middle">${escapeHtml(row.date.slice(5))}</text>`;}).join("");box.innerHTML=`<div class="backtest-summary"><div><span>BUY</span><b>${number(result.buy_signals,0)}</b></div><div><span>SELL</span><b>${number(result.sell_signals,0)}</b></div><div><span>TRADES TAKEN</span><b>${number(result.trades_taken,0)}</b></div><div><span>PLANNED RISK</span><b>${inr(result.planned_risk)}</b></div></div><div class="backtest-chart-panel"><div class="chart-head"><div><strong>Signals by day</strong><small>Directional strategy outputs after the backtest rules are applied</small></div><span>${daily.length} active day${daily.length===1?"":"s"}</span></div>${daily.length?`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Backtest signals by day"><line class="chart-axis" x1="${left}" y1="${top+plotH}" x2="${width-right}" y2="${top+plotH}"/>${bars}</svg>`:empty("No directional signals","◇","The selected period produced no approved BUY or SELL outputs.")}</div><div class="backtest-metrics">${Object.entries(result.metrics||{}).filter(([key])=>!["rating","rating_label","breakdown"].includes(key)).map(([key,value])=>`<div><span>${escapeHtml(key.replaceAll("_"," "))}</span><b>${escapeHtml(typeof value==="number"?number(value,2):String(value))}</b></div>`).join("")}<div><span>Rating</span><b>${escapeHtml(result.metrics?.rating_label||result.metrics?.rating||"—")}</b></div></div><div class="backtest-signal-list">${(result.signals||[]).slice(-20).reverse().map(s=>`<div><span class="${String(s.direction).toLowerCase()}">${escapeHtml(s.direction)}</span><b>${escapeHtml(timestamp(s.timestamp))}</b><small>${escapeHtml(s.reason||"")}</small></div>`).join("")||empty("No directional signals","◇")}</div>`;box.hidden=false;}
async function runBacktest(){const strategy=$("backtestStrategy").value,symbol=$("backtestSymbol").value,period=$("backtestPeriod").value,button=$("runBacktestButton");button.disabled=true;$("backtestStatus").className="backtest-status loading";$("backtestStatus").textContent="Fetching real Yahoo candles and running the canonical strategy…";try{const response=await fetch(`/api/backtest?${new URLSearchParams({strategy,symbol,period})}`,{cache:"no-store"});const result=await response.json();state.backtest=result;renderBacktest(result);}catch(error){state.backtest={ok:false,error:error.message};renderBacktest(state.backtest);}finally{button.disabled=false;}}
async function loadCalendar(){const impact=state.calendarImpacts.has("All")?"All":[...state.calendarImpacts].join(",");$("calendarItems").innerHTML=empty("Loading calendar…","◉","Reading the saved Forex Factory feed.");try{const url=`/api/calendar?${new URLSearchParams({date:state.calendarDate,impact})}`;const response=await fetch(url,{cache:"no-store"});state.calendar=await response.json();renderCalendar();}catch(error){state.calendar={status:"OFFLINE",source:"Forex Factory",message:error.message,items:[],counts:{}};renderCalendar();}}
async function showConnectionStatus(online,message=""){const banner=$("connectionBanner"),status=$("systemStatus"),badge=$("systemStatusBadge");if(banner){banner.hidden=online;if(!online)banner.textContent=message||"Dashboard connection problem.";}if(status)status.textContent=online?"ONLINE":"OFFLINE";if(badge)badge.classList.toggle("offline",!online);}
function renderSafely(name,fn){try{fn();}catch(error){console.error(`Dashboard render failed: ${name}`,error);}}
async function loadDashboard(){try{const response=await fetch(`${CONFIG.apiUrl}?t=${Date.now()}`,{cache:"no-store"});if(!response.ok)throw new Error(`Dashboard API ${response.status}`);const payload=await response.json();if(!payload||payload.ok===false)throw new Error(payload?.error||"Dashboard API returned an invalid snapshot.");state.data=payload;state.lastUpdate=payload.generated_at||new Date().toISOString();showConnectionStatus(true);renderSafely("overview",renderOverview);renderSafely("signals",renderSignals);renderSafely("history",renderHistory);renderSafely("tools",renderTools);if(state.activePage==="calendar")renderSafely("calendar",loadCalendar);}catch(error){console.error("Dashboard load failed",error);showConnectionStatus(false,`Dashboard connection problem: ${error.message}`);}}
function setPage(page){state.activePage=page;$$('.page').forEach(el=>el.classList.toggle('active',el.id===`page-${page}`));$$('.nav-button').forEach(el=>el.classList.toggle('active',el.dataset.page===page));if(page==="calendar")loadCalendar();window.scrollTo({top:0,behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"});}
function resolveTheme(theme){return theme==="system"?(window.matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light"):theme;}function applyTheme(theme){const choice=["light","dark","system"].includes(theme)?theme:"light";document.documentElement.dataset.theme=resolveTheme(choice);document.documentElement.dataset.themeChoice=choice;localStorage.setItem("mavis-theme",choice);applyAppearanceControls();}
function applyStyle(style){const value=style==="neo"?"neo":"modern";document.documentElement.dataset.style=value;localStorage.setItem("mavis-style",value);applyAppearanceControls();}
function applyAppearanceControls(){$$('[data-theme-choice]').forEach(b=>b.classList.toggle("active",b.dataset.themeChoice===(document.documentElement.dataset.themeChoice||document.documentElement.dataset.theme)));$$('[data-style-choice]').forEach(b=>b.classList.toggle("active",b.dataset.styleChoice===document.documentElement.dataset.style));const compact=localStorage.getItem("mavis-compact")==="true",motion=localStorage.getItem("mavis-reduce-motion")==="true";document.documentElement.dataset.compact=compact?"true":"false";document.documentElement.dataset.reduceMotion=motion?"true":"false";const c=$("compactModeToggle"),m=$("reduceMotionToggle");if(c)c.classList.toggle("active",compact);if(m)m.classList.toggle("active",motion);}
function initAppearance(){const theme=localStorage.getItem("mavis-theme")||"light",style=localStorage.getItem("mavis-style")||"modern";document.documentElement.dataset.style=style;applyTheme(theme);}
function bindEvent(id,event,handler){const el=$(id);if(!el){console.warn(`Dashboard control missing: #${id}`);return;}el.addEventListener(event,handler);}
function bindEvents(){
$$('[data-page]').forEach(button=>button.addEventListener("click",()=>setPage(button.dataset.page)));
$$('[data-page-link]').forEach(button=>button.addEventListener("click",()=>setPage(button.dataset.pageLink)));
bindEvent("refreshButton","click",loadDashboard);
bindEvent("signalsRefreshButton","click",loadDashboard);
bindEvent("historyRefreshButton","click",loadDashboard);
bindEvent("themeToggle","click",()=>applyTheme(document.documentElement.dataset.theme==="dark"?"light":"dark"));
$$('[data-theme-choice]').forEach(button=>button.addEventListener("click",()=>applyTheme(button.dataset.themeChoice)));
bindEvent("compactModeToggle","click",()=>{const next=localStorage.getItem("mavis-compact")!=="true";localStorage.setItem("mavis-compact",String(next));applyAppearanceControls();});
bindEvent("reduceMotionToggle","click",()=>{const next=localStorage.getItem("mavis-reduce-motion")!=="true";localStorage.setItem("mavis-reduce-motion",String(next));applyAppearanceControls();});
bindEvent("styleToggle","click",()=>applyStyle(document.documentElement.dataset.style==="neo"?"modern":"neo"));
bindEvent("runBacktestButton","click",runBacktest);
bindEvent("backtestStrategy","change",()=>{state.backtest=null;renderTools();});
bindEvent("calendarRefreshButton","click",loadCalendar);
document.addEventListener("click",event=>{const calendarDateGroup=event.target.closest("[data-calendar-date-group]");if(calendarDateGroup){const key=calendarDateGroup.dataset.calendarDateGroup;if(state.calendarDates.has(key))state.calendarDates.delete(key);else state.calendarDates.add(key);renderSafely("calendar",renderCalendar);return;}const signalDate=event.target.closest("[data-signal-date]");if(signalDate){const key=signalDate.dataset.signalDate;if(state.signalDates.has(key))state.signalDates.delete(key);else state.signalDates.add(key);renderSafely("signals",renderSignals);return;}const historyDate=event.target.closest("[data-history-date]");if(historyDate){const key=historyDate.dataset.historyDate;if(state.historyTradeDates.has(key))state.historyTradeDates.delete(key);else state.historyTradeDates.add(key);renderSafely("history",renderHistory);return;}const trigger=event.target.closest("[data-expand]");if(!trigger)return;const key=trigger.dataset.expand;if(state.expanded.has(key))state.expanded.delete(key);else state.expanded.add(key);renderSafely("overview",renderOverview);renderSafely("signals",renderSignals);renderSafely("history",renderHistory);if(state.calendar)renderSafely("calendar",renderCalendar);});
}
function bootstrapDashboard(){try{initAppearance();bindEvents();const marketClock=$("marketClock");if(marketClock){marketClock.textContent=clock();setInterval(()=>{const clockEl=$("marketClock");if(clockEl)clockEl.textContent=clock();},1000);}loadDashboard();setInterval(loadDashboard,CONFIG.refreshMs);}catch(error){console.error("Dashboard bootstrap failed",error);showConnectionStatus(false,"Dashboard startup problem. Check browser console.");}}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bootstrapDashboard,{once:true});else bootstrapDashboard();

function renderScanHistory(){const rows=Array.isArray(state.data?.scan_history)?state.data.scan_history:[];const el=$("scanHistory");if(!el)return;el.innerHTML=rows.length?rows.slice(0,20).map(r=>{const p=r.payload||{};return `<div class="scan-history-row"><b>${escapeHtml(r.strategy_id||"Strategy")}</b><span>${escapeHtml(r.status||"—")}</span><small>${number(p.checked,0)} checked · ${number(p.directional,0)} directional · ${number(p.sent,0)} sent · ${number(p.errors,0)} errors</small></div>`}).join(""):empty("No scan history yet","◇","Completed scans are persisted here.");}

function openTradeDetail(trade){const plan=trade.plan||trade,status=String(trade.status||"OPEN").toUpperCase(),side=String(plan.side||trade.type||"").toUpperCase(),symbol=trade.symbol||plan.symbol||"Paper trade",label=assetLabel(symbol,trade.label||plan.label),strategy=strategyLabel(plan.strategy||trade.strategy),pnl=trade.pnl;let drawer=document.getElementById("tradeDetailDrawer");if(!drawer){drawer=document.createElement("div");drawer.id="tradeDetailDrawer";drawer.className="trade-drawer-shell";document.body.appendChild(drawer);drawer.addEventListener("click",e=>{if(e.target===drawer||e.target.closest("[data-close-trade-detail]"))drawer.classList.remove("open");});}drawer.innerHTML=`<aside class="trade-drawer" role="dialog" aria-modal="true" aria-label="Trade details"><button class="drawer-close" type="button" data-close-trade-detail>×</button><span class="eyebrow">TRADE DETAIL</span><h2>${escapeHtml(label)}</h2><div class="drawer-status"><span class="trade-status ${status.toLowerCase()}">${status}</span><b>${escapeHtml(side||"—")}</b></div><div class="drawer-price-grid"><div><span>Entry</span><b>${price(plan.entry??trade.entry)}</b></div><div><span>Current / Exit</span><b>${status==="CLOSED"?price(trade.exit_price):price(trade.current_price??trade.last_price)}</b></div><div><span>Stop loss</span><b>${price(plan.stop_loss??trade.sl)}</b></div><div><span>Take profit</span><b>${price(plan.take_profit??trade.tp)}</b></div></div><section><h3>Signal details</h3><div class="drawer-details"><div><span>Strategy</span><b>${escapeHtml(strategy)}</b></div><div><span>Account</span><b>${escapeHtml(String(trade.account||"nifty").toUpperCase())}</b></div><div><span>Quantity</span><b>${number(plan.quantity??trade.qty,4)}</b></div><div><span>Planned risk</span><b>${inr(plan.planned_risk??trade.planned_risk)}</b></div><div><span>Signal created</span><b>${escapeHtml(timestamp(plan.signal_timestamp||trade.signal_ts||trade.created_at))}</b></div>${status==="CLOSED"?`<div><span>P/L</span><b class="${Number(pnl)>=0?"positive":"negative"}">${inr(pnl)}</b></div><div><span>Closed</span><b>${escapeHtml(timestamp(trade.closed_at||trade.exit_timestamp))}</b></div><div><span>Exit reason</span><b>${escapeHtml(trade.exit_reason||trade.result||"—")}</b></div>`:""}</div></section></aside>`;requestAnimationFrame(()=>drawer.classList.add("open"));}
